openapi: 3.0.0
servers:
  - url: "https://api.dolby.com"
security:
  - "x-apikey": []
info:
  title: Music
  description: |
    Submit jobs to receive descriptive word tags about the contents of a music media file.

    POST to start a job and GET with the returned job_id to check progress.
  version: "0.0.0"
  contact:
    email: support@dlby.io
tags:
  - name: analyze
    description: Operations for analyzing the content of a music media file
components:
  securitySchemes:
    "x-apikey":
      name: x-apikey
      type: apiKey
      in: header
paths:
  "/beta/media/analyze/music":
    post:
      tags:
        - analyze
      summary: Start Music Analysis
      operationId: postAnalyzeMusic
      description: |
        The Music Analysis API calculates descriptive word tags for your content.
      security:
        - "x-apikey": []
      requestBody:
        required: true
        description: |
          Asnynchronous operation, provide required input and
          output parameters.
        content:
          "application/json":
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  $ref: '/api-spec/requests.yaml#/components/parameters/StandardInput'
                top_n:
                  type: number
                  default: 3
                  example: 3
                  description: The number of tags to include in results.
                confidences:
                  type: boolean
                  default: false
                  example: false
                  description: Controls whether the confidence levels of each tags are returned
      responses:
        '200':
          description: |
              Request Accepted OK.
              Call GET with your job_id to check on the status of the result.
          content:
            "application/json":
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    description: Unique identifier for this long-running job
                    example: "a293a26a-8c77-46bf-8eb6-aecc8649d524"
        '400':
          description: |
              Bad Request.
              The body of the response will give additional details and you
              may need to double-check the provided parameters.
        '401':
          description: |
              Authentication Failed.
              Make sure you are providing your API Key in the x-apikey header
              of the request.
    get:
      tags:
        - analyze
      summary: Check Status of Music Analysis
      operationId: getAnalyzeMusic
      description: |
        Retrieve the status of a processing job by job_id.
      security:
        - "x-apikey": []
      parameters:
        - name: job_id
          in: query
          description: Unique job_id for a submitted asynchronous processing job
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            Status of this job.  When completed successfully you can find the analysis in the result of the response.
          content:
            "application/json":
              schema:
                type: object
                required:
                  - status
                  - path
                  - progress
                properties:
                  status:
                    type: string
                    description: The status of the job while it is being processed.
                    example: Success
                    enum:
                      - Pending
                      - Failed
                      - Running
                      - Success
                      - InternalError
                  path:
                    type: string
                    description: The endpoint you are using
                    example: "/beta/media/analyze/loudness"
                  progress:
                    type: integer
                    description: An estimate of how much progress has been made processing the file
                    example: 100
                  result:
                    type: object
                    required:
                      - tags
                    properties:
                        tags:
                            type: object
                            required:
                                - tag
                            properties:
                                tag:
                                    type: string
                                    example: "Rock"
                                confidence:
                                    type: number
                                    format: float
                                    description: Confidence in the tag
                                    example: 0.473465
                                    maximum: 100
                                    minimum: 0
                  error:
                    type: object
                    properties:
                      title:
                        type: string
                        example: An internal service error has occurred
                      type:
                        type: string
                        example: "/problems/internal-error"
        '404':
          description: |
            The job for the given job_id was not found
